---
title: "First Knit"
author: "Michelle Benavides"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended high school in Palmdale, CA in a school named Palmdale High School. I did graduate, and I graduated in June of 2020. When I compare my english class to my math class, I get a bit embarrassed. I get embarrassed because I actually grew up loving math and it came naturally to me, while I would be struggling in my english class. However, my best subject was any art class that I took. I took drawing 1 and painting 1, which made me feel like I could be really creative. 

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  Since I am required to have a computer I can use in class and at home I chose to use my Apple Macbook Pro. So far it has worked pretty smoothly and I really hope I do not experience any problems. I would rate my computer skills at around a 7. Simply because I do not know everything, but if someone were to show me how to do something I would remember it pretty well. The internet access that I have at my house is pretty spotty in some areas of the house, but in my room it has been really good. Also, if I ever have internet problems I usually go to Starbucks where they have really good internet and allow people to do homework there. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  Honestly, anyone can call me whatever they please. However, my close friends and family call me "Miche" or "Prieta" (which means "brown girl" in Spanish). Most people do just refer to me simply as "Michelle".
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  To be completely honest, I strive to achieve happiness in life and I want to help immigrants, like Hispanics and others, to also achieve happiness in the United States. I think the college subject that would be of the greatest interest to me is Political Science, more specifically Foreign politics or international relations. Another subject would be world languages because I want to be able to communicate with more people. 
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  Over the years, I have gone to foreign countries with my family. Every year me and my family go to Mexico to spend some time with my Aunts and Uncles. I wish to one day be able to go to Peru, France, and Rome with my partner. I have never been in the military and as of right now I never plan to be. However, if I got drafted I would choose to go into the Navy because I can not swim to be in the Marines and I do not know other branches. 
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I already took Math 115 in my first year of college for my major. Then, I decided I wanted to transfer to a University of California so my couselor recommended that I also take Math 116. I did know that Math 115 only satisfies a general education requirement and that Math 116 counts as taking statistics in several transfer institutions. In the beginning I was just not sure if I wanted to transfer. I need to obtain at least a "B" but I want to strive for an "A" so that I can transfer to UCLA.
   
 






  




